const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
(async()=>{
 const calls=[],dialogs=[],messages=[];let requested,reloaded=false,dirty=false;
 const preview={token:'TOKEN',reason:'<img src=x onerror=alert(1)>',before:{verified_hours:2},after:{verified_hours:1},financial_before:{settlement_amount:280},proposed_amount:140,settlement_blockers:[],dependencies:[]};
 const ctx={__:x=>x,powerpro:{checkin_overtime:{}},frappe:{provide(){},utils:{escape_html:s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')},
  prompt(fields,fn){assert(fields[0].reqd);requested=fn;},msgprint(m){messages.push(m)},call(args){calls.push(args);return Promise.resolve({message:preview})},ui:{Dialog:function(args){Object.assign(this,args);this.show=()=>{};this.hide=()=>{};dialogs.push(this);}}}};
 vm.runInNewContext(fs.readFileSync('powerpro/public/js/checkin_overtime.js','utf8'),ctx);
 const frm={doc:{name:'AUTH'},is_dirty:()=>dirty,reload_doc(){reloaded=true;}};
 dirty=true;ctx.powerpro.checkin_overtime.review(frm);assert.equal(requested,undefined);
 dirty=false;ctx.powerpro.checkin_overtime.review(frm);requested({reason:'reason'});await Promise.resolve();
 assert.equal(calls[0].method,'powerpro.controllers.checkin_overtime_review.preview_review');
 assert(dialogs[0].fields[0].options.includes('&lt;img'));assert(!dialogs[0].fields[0].options.includes('<img'));
 assert(dialogs[0].fields[0].options.includes('140'));
 dirty=true;dialogs[0].primary_action();assert.equal(calls.length,1);
 dirty=false;dialogs[0].primary_action();await Promise.resolve();
 assert.equal(calls[1].type,'POST');assert.equal(calls[1].args.token,'TOKEN');assert.equal(calls[1].args.authorization,'AUTH');assert(reloaded);
 const declaration={full_session:true,reference:'<document>',intervals:[{start:'2026-09-14 08:00:00',end:'2026-09-14 20:00:00'}]};
 preview.manual_declaration=declaration;preview.checkin_comparison={source_checkins:[{name:'CHK',time:'2026-09-14 08:00:00',log_type:'IN'}]};
 ctx.powerpro.checkin_overtime.review(frm,true);requested({reason:'HR statement',...declaration});await Promise.resolve();
 assert.equal(JSON.parse(calls[2].args.manual_declaration).full_session,true);
 assert(dialogs[1].fields[0].options.includes('&lt;document&gt;'));assert(dialogs[1].fields[0].options.includes('CHK'));
 dialogs[1].primary_action();await Promise.resolve();assert.deepEqual(JSON.parse(calls[3].args.manual_declaration),declaration);
 frm.doc.doctype='Retroactive Overtime Adjustment';frm.doc.name='AJUSTE';
 ctx.powerpro.checkin_overtime.review(frm);requested({reason:'Retroactive correction'});await Promise.resolve();
 assert.equal(calls[4].args.source_type,'Retroactive Overtime Adjustment');
 dialogs[2].primary_action();await Promise.resolve();assert.equal(calls[5].args.source_type,'Retroactive Overtime Adjustment');assert.equal(calls[5].args.authorization,'AJUSTE');
 frm.doc.docstatus=2;preview.historical_only=true;preview.worked_hours_before=11;preview.worked_hours_after=10;
 ctx.powerpro.checkin_overtime.review(frm);requested({reason:'Historical physical correction'});await Promise.resolve();
 assert.equal(calls[6].method,'powerpro.controllers.overtime_history.preview_review');assert(dialogs[3].fields[0].options.includes('Sin cambios'));
 dialogs[3].primary_action();await Promise.resolve();assert.equal(calls[7].method,'powerpro.controllers.overtime_history.apply_review');
 frm.doc.docstatus=0;preview.historical_only=false;preview.draft_only=true;
 ctx.powerpro.checkin_overtime.review(frm,true);requested({reason:'Initial declaration',...declaration});await Promise.resolve();
 assert.equal(calls[8].method,'powerpro.controllers.retroactive_draft_review.preview_review');
 assert(dialogs[4].fields[0].options.includes('El ajuste sigue en borrador'));
 dialogs[4].primary_action();await Promise.resolve();assert.equal(calls[9].method,'powerpro.controllers.retroactive_draft_review.apply_review');
 frm.doc.docstatus=2;
 const historicalButtons=[];frm.add_custom_button=(label,fn)=>historicalButtons.push({label,fn});
 preview.applicable=true;preview.can_review=true;preview.manual_review_allowed=true;
 ctx.powerpro.checkin_overtime.add_history_actions(frm);await Promise.resolve();
 assert(historicalButtons.some(b=>b.label==='Revisar trabajo histórico'));assert(historicalButtons.some(b=>b.label==='Declarar jornada histórica'));
 console.log('HR review UI: required reason, escaped preview, before/after amount, dirty guards and explicit token-bound POST passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
